export default {
    products: [
                {
                    _id: 1,
                    name: 'Slim Shirt',
                    category: 'Shirt',
                    image: '/images/d1.jpg',
                    price: 60,
                    brand: 'Nike',
                    rating: 4.5,
                    numReviews: 10, 
                    countInStock: 6,
                },
                {
                    _id: 2,
                    name: 'Slim Shirt',
                    category: 'Shirt',
                    image: '/images/d1.jpg',
                    price: 50,
                    brand: 'Nike',
                    rating: 4.2,
                    numReviews: 5,
                    countInStock: 5,
                },
                {
                    _id: 3,
                    name: 'Nice Pant',
                    image: '/images/d1.jpg',
                    price: 70,
                    brand: 'Rich Man',
                    rating: 4.1,
                    numReviews: 13,
                    countInStock: 3,
                },
                {
                    _id: 4,
                    name: 'Formal Shirt',
                    category: 'Shirt',
                    image: '/images/d1.jpg',
                    price: 48,
                    brand: 'Arong',
                    rating: 4.25,
                    numReviews: 8,
                    countInStock: 4,
                },
                {
                    _id: 5,
                    name: 'Jins Pant',
                    image: '/images/d1.jpg',
                    price: 70,
                    brand: 'Nike',
                    rating: 4.3,
                    numReviews: 9,
                    countInStock: 7,
                },
                {
                    _id: 6,
                    name: 'Half Sirt',
                    image: '/images/d1.jpg',
                    price: 70,
                    brand: 'Eagle',
                    rating: 4.00,
                    numReviews: 6,
                    countInStock: 2,
                }
        ]
};